### ISSUE TITLE
Add form-builder sub-project

### ISSUE THREAD

**Issue by backpackcoder** [backpackcoder/miniature-octo-tribble#14]
Create a sub section of this application to examine form-model bindings between various frameworks.

Create froms in various HTML UI frameworks
 - [x] #15 vanilla HTML form
 - [x] #16 Bootstrap v3 form
 - [x] #16 Bootstrap v4 form
 - [x] #17 Semantic UI form
 - [ ] #18 Add comparison page

**Comment by backpackcoder** [comment]
Create froms in various HTML UI frameworks
[ ] #15 vanilla HTML form
[ ] #16 Bootstrap v3 form
[ ] #16 Bootstrap v4 form
[ ] #17 Semantic UI form
